# TODO: gestionar volumenes de forma adecuada
# montarlos fuera de srcs
services:
  nginx:
    image: iubieta/nginx:latest
    build: nginx/
    ports:
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl:ro

  mariadb:
    image: iubieta/mariadb:latest
    build: mariadb/
    ports:
      - 3306:3306
    env_file:
      - .env

  wordpress:
    image: iubieta/wordpress:latest
    build: wordpress/
    ports:
      - 9000:9000
    volumes:
      - ./wordpress/data:/var/www/html
