volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/iubieta-/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/iubieta-/data/mariadb

services:
  nginx:
    image: iubieta/nginx:latest
    build: nginx/
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    secrets:
      - site_crt
      - site_key

  mariadb:
    image: iubieta/mariadb:latest
    build: mariadb/
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    secrets:
      - db_pass
      - db_root_pass

  wordpress:
    image: iubieta/wordpress:latest
    build: wordpress/
    ports:
      - 9000:9000
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    secrets:
      - wp_user_pass
      - wp_admin_pass

secrets:
  site_crt:
    file: site.crt
  site_key:
    file: site.key
  db_pass:
    file: db_pass.txt
  db_root_pass:
    file: db_root_pass.txt
  wp_user_pass:
    file: wp_user_pass.txt
  wp_admin_pass:
    file: wp_admin_pass.txt
