networks:
  inception:
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/iubieta-/data/wordpress
  
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/iubieta-/data/mariadb

services:
  nginx:
    image: iubieta/nginx:1.0
    build: requirements/nginx/
    env_file:
      - .env
    networks:
        - inception
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    secrets:
      - site_crt
      - site_key
    restart: unless-stopped

  mariadb:
    image: iubieta/mariadb:1.0
    build: requirements/mariadb/
    networks:
        - inception
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    secrets:
      - db_pass
      - db_root_pass
    restart: unless-stopped

  wordpress:
    image: iubieta/wordpress:1.0
    build: requirements/wordpress/
    networks:
        - inception
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    secrets:
      - db_pass
      - wp_user_pass
      - wp_admin_pass
    restart: unless-stopped

secrets:
  site_crt:
    file: ../secrets/site.crt
  site_key:
    file: ../secrets/site.key
  db_pass:
    file: ../secrets/db_password.txt
  db_root_pass:
    file: ../secrets/db_root_password.txt
  wp_user_pass:
    file: ../secrets/wp_user_password.txt
  wp_admin_pass:
    file: ../secrets/wp_admin_password.txt
