server {
    listen 443 ssl;
    server_name iubieta-.42.fr;

    ssl_certificate     /etc/nginx/ssl/iubieta.crt;
    ssl_certificate_key /etc/nginx/ssl/iubieta.key;
    ssl_protocols       TLSv1.2 TLSv1.3;

}

